version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-rates_service_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${DB_NAME:-rates_service_db} -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - config.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-rates_service_db}
      GRPC_ADDRESS: :5001
      LOG_LEVEL: info
      SERVICE_NAME: rates-service
      OTLP_ENDPOINT: otel-collector:4317
      HEALTHCHECK_ENDPOINT: 0.0.0.0:8080
      GRINEX_PAIRS_JSON: /app/configs/pairs.json
      GRINEX_API_URL: https://grinex.io/api/v1/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    ports:
      - "8080:8080"
      - "5001:5001"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317" # OTLP gRPC receiver

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - jaeger

volumes:
  postgres_data:
