// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rates_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Метод расчета конечной цены из стакана
type CalcMethod int32

const (
	CalcMethod_CALC_METHOD_UNSPECIFIED CalcMethod = 0
	CalcMethod_CALC_METHOD_TOP_N       CalcMethod = 1
	CalcMethod_CALC_METHOD_AVG_N_M     CalcMethod = 2
)

var CalcMethod_name = map[int32]string{
	0: "CALC_METHOD_UNSPECIFIED",
	1: "CALC_METHOD_TOP_N",
	2: "CALC_METHOD_AVG_N_M",
}

var CalcMethod_value = map[string]int32{
	"CALC_METHOD_UNSPECIFIED": 0,
	"CALC_METHOD_TOP_N":       1,
	"CALC_METHOD_AVG_N_M":     2,
}

func (x CalcMethod) String() string {
	return proto.EnumName(CalcMethod_name, int32(x))
}

func (CalcMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_58acc8f0047eb542, []int{0}
}

type GetRatesRequest struct {
	// Валютная пара (например, "USDT_RUB")
	Pair string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	// Метод агрегации данных из стакана (TopN или AvgNM)
	CalcMethod CalcMethod `protobuf:"varint,2,opt,name=calc_method,json=calcMethod,proto3,enum=grinex.v1.CalcMethod" json:"calc_method,omitempty"`
	// Параметр N (индекс для TopN или начало диапазона для AvgNM)
	N int32 `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	// Параметр M (конец диапазона, используется только для AvgNM)
	M                    int32    `protobuf:"varint,4,opt,name=m,proto3" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatesRequest) Reset()         { *m = GetRatesRequest{} }
func (m *GetRatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatesRequest) ProtoMessage()    {}
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58acc8f0047eb542, []int{0}
}

func (m *GetRatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatesRequest.Unmarshal(m, b)
}
func (m *GetRatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatesRequest.Marshal(b, m, deterministic)
}
func (m *GetRatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatesRequest.Merge(m, src)
}
func (m *GetRatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatesRequest.Size(m)
}
func (m *GetRatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatesRequest proto.InternalMessageInfo

func (m *GetRatesRequest) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *GetRatesRequest) GetCalcMethod() CalcMethod {
	if m != nil {
		return m.CalcMethod
	}
	return CalcMethod_CALC_METHOD_UNSPECIFIED
}

func (m *GetRatesRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *GetRatesRequest) GetM() int32 {
	if m != nil {
		return m.M
	}
	return 0
}

type GetRatesResponse struct {
	// Рассчитанная цена продажи (Ask)
	Ask float64 `protobuf:"fixed64,1,opt,name=ask,proto3" json:"ask,omitempty"`
	// Рассчитанная цена покупки (Bid)
	Bid float64 `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	// Unix timestamp в миллисекундах для высокой точности
	TimestampMs          int64    `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatesResponse) Reset()         { *m = GetRatesResponse{} }
func (m *GetRatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatesResponse) ProtoMessage()    {}
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58acc8f0047eb542, []int{1}
}

func (m *GetRatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatesResponse.Unmarshal(m, b)
}
func (m *GetRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatesResponse.Marshal(b, m, deterministic)
}
func (m *GetRatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatesResponse.Merge(m, src)
}
func (m *GetRatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatesResponse.Size(m)
}
func (m *GetRatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatesResponse proto.InternalMessageInfo

func (m *GetRatesResponse) GetAsk() float64 {
	if m != nil {
		return m.Ask
	}
	return 0
}

func (m *GetRatesResponse) GetBid() float64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *GetRatesResponse) GetTimestampMs() int64 {
	if m != nil {
		return m.TimestampMs
	}
	return 0
}

type HealthCheckResponse struct {
	// Статус сервиса (true = жив и БД отвечает)
	IsHealthy bool `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	// Опциональное сообщение (например, "OK" или текст ошибки БД)
	StatusMessage        string   `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58acc8f0047eb542, []int{2}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetIsHealthy() bool {
	if m != nil {
		return m.IsHealthy
	}
	return false
}

func (m *HealthCheckResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("grinex.v1.CalcMethod", CalcMethod_name, CalcMethod_value)
	proto.RegisterType((*GetRatesRequest)(nil), "grinex.v1.GetRatesRequest")
	proto.RegisterType((*GetRatesResponse)(nil), "grinex.v1.GetRatesResponse")
	proto.RegisterType((*HealthCheckResponse)(nil), "grinex.v1.HealthCheckResponse")
}

func init() {
	proto.RegisterFile("proto/rates_service.proto", fileDescriptor_58acc8f0047eb542)
}

var fileDescriptor_58acc8f0047eb542 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x61, 0x6b, 0xd4, 0x40,
	0x14, 0x74, 0x7b, 0x55, 0x7a, 0xef, 0x6a, 0x8d, 0x5b, 0x6a, 0xcf, 0x3b, 0x94, 0xf3, 0x40, 0x38,
	0x04, 0x13, 0x5a, 0xc1, 0x2f, 0x7e, 0xaa, 0x69, 0x6c, 0x0b, 0xe6, 0x5a, 0xb6, 0x55, 0xa8, 0x7e,
	0x58, 0x36, 0xf1, 0x99, 0xc4, 0xbb, 0x4d, 0x62, 0x76, 0x53, 0xcc, 0x4f, 0xf1, 0xdf, 0x4a, 0x76,
	0xed, 0x35, 0x94, 0xfb, 0x36, 0x6f, 0x66, 0x99, 0x61, 0xe7, 0x3d, 0x78, 0x5e, 0x56, 0x85, 0x2e,
	0xbc, 0x4a, 0x68, 0x54, 0x5c, 0x61, 0x75, 0x93, 0xc5, 0xe8, 0x1a, 0x8e, 0xf6, 0x93, 0x2a, 0xcb,
	0xf1, 0x8f, 0x7b, 0x73, 0x30, 0x1a, 0x27, 0x45, 0x91, 0x2c, 0xd1, 0x33, 0x42, 0x54, 0xff, 0xf4,
	0x50, 0x96, 0xba, 0xb1, 0xef, 0xa6, 0x0d, 0x3c, 0x39, 0x41, 0xcd, 0x5a, 0x07, 0x86, 0xbf, 0x6b,
	0x54, 0x9a, 0x52, 0xd8, 0x2c, 0x45, 0x56, 0x0d, 0xc9, 0x84, 0xcc, 0xfa, 0xcc, 0x60, 0xfa, 0x1e,
	0x06, 0xb1, 0x58, 0xc6, 0x5c, 0xa2, 0x4e, 0x8b, 0x1f, 0xc3, 0x8d, 0x09, 0x99, 0xed, 0x1c, 0xee,
	0xb9, 0xab, 0x10, 0xd7, 0x17, 0xcb, 0x38, 0x34, 0x22, 0x83, 0x78, 0x85, 0xe9, 0x36, 0x90, 0x7c,
	0xd8, 0x9b, 0x90, 0xd9, 0x43, 0x46, 0xf2, 0x76, 0x92, 0xc3, 0x4d, 0x3b, 0xc9, 0xe9, 0x35, 0x38,
	0x77, 0xd1, 0xaa, 0x2c, 0x72, 0x85, 0xd4, 0x81, 0x9e, 0x50, 0x0b, 0x13, 0x4d, 0x58, 0x0b, 0x5b,
	0x26, 0xca, 0x6c, 0x22, 0x61, 0x2d, 0xa4, 0xaf, 0x60, 0x5b, 0x67, 0x12, 0x95, 0x16, 0xb2, 0xe4,
	0x52, 0x19, 0xfb, 0x1e, 0x1b, 0xac, 0xb8, 0x50, 0x4d, 0xbf, 0xc3, 0xee, 0x29, 0x8a, 0xa5, 0x4e,
	0xfd, 0x14, 0xe3, 0xc5, 0xca, 0xfd, 0x05, 0x40, 0xa6, 0x78, 0x6a, 0x94, 0xc6, 0x84, 0x6c, 0xb1,
	0x7e, 0xa6, 0xec, 0xd3, 0x86, 0xbe, 0x86, 0x1d, 0xa5, 0x85, 0xae, 0x15, 0x97, 0xa8, 0x94, 0x48,
	0xd0, 0xa4, 0xf6, 0xd9, 0x63, 0xcb, 0x86, 0x96, 0x7c, 0x73, 0x0d, 0x70, 0xf7, 0x5b, 0x3a, 0x86,
	0x7d, 0xff, 0xe8, 0xb3, 0xcf, 0xc3, 0xe0, 0xea, 0xf4, 0xfc, 0x98, 0x7f, 0x99, 0x5f, 0x5e, 0x04,
	0xfe, 0xd9, 0xa7, 0xb3, 0xe0, 0xd8, 0x79, 0x40, 0xf7, 0xe0, 0x69, 0x57, 0xbc, 0x3a, 0xbf, 0xe0,
	0x73, 0x87, 0xd0, 0x7d, 0xd8, 0xed, 0xd2, 0x47, 0x5f, 0x4f, 0xf8, 0x9c, 0x87, 0xce, 0xc6, 0xe1,
	0x5f, 0x02, 0x83, 0xb6, 0x90, 0x4b, 0xbb, 0x4b, 0xea, 0xc3, 0xd6, 0x6d, 0x45, 0x74, 0xd4, 0x69,
	0xfb, 0xde, 0xca, 0x46, 0xe3, 0xb5, 0xda, 0xff, 0x5f, 0x07, 0x30, 0xe8, 0x94, 0x41, 0x9f, 0xb9,
	0xf6, 0x1e, 0xdc, 0xdb, 0x7b, 0x70, 0x83, 0xf6, 0x1e, 0x46, 0x2f, 0x3b, 0x1e, 0x6b, 0xca, 0xfb,
	0x78, 0xf0, 0xcd, 0x4b, 0x32, 0x9d, 0xd6, 0x91, 0x1b, 0x17, 0xd2, 0x6b, 0x8a, 0xba, 0x7a, 0x5b,
	0x2b, 0xac, 0x72, 0x21, 0xd1, 0x4e, 0x65, 0x55, 0xfc, 0xc2, 0x58, 0x7b, 0xe5, 0x22, 0xf1, 0xca,
	0xe8, 0x43, 0x19, 0x45, 0x8f, 0x4c, 0xc4, 0xbb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x83,
	0xf3, 0xf6, 0xa8, 0x02, 0x00, 0x00,
}
